type Cargo {
	id: ID!
	nombre: String!
	estado: Boolean!
	personal(pagina: Int, cantidad: Int): [Personal!]!
}

type Query {
	listarCargo(filtro: String, pagina: Int, cantidad: Int): [Cargo!]!
}

type Mutation {
	registrarCargo(nombre: String!): Cargo
	modificarCargo(id: ID!, nombre: String, estado: Boolean): Cargo
	eliminarCargo(id: ID!): Cargo
}
