type Credencial {
	id: ID!
	usuario: String!
	clave: String!
	estado: Boolean!
	rol: Rol!
	personal: Personal!
}

type Query {
	login(usuario: String!, clave: String!): Autenticacion
	usuarioActual: Personal
}

type Mutation {
	registrarCredencial(
		usuario: String!
		clave: String!
		personal: ID!
	): Credencial
	modificarCredencial(
		id: ID!
		usuario: String
		clave: String
		estado: Boolean
	): Credencial
	eliminarCredencial(id: ID!): Credencial
}

type Autenticacion {
	token: String!
	personal: Personal!
}

enum Rol {
	ADMIN
	USUARIO
}
