type Mesa {
	id: ID!
	numero: Int!
	ocupado: Boolean!
	estado: Boolean!
	pedidoActual: Pedido
	pedidosRealizados(pagina: Int, cantidad: Int): [Pedido!]!
}

type Query {
	listarMesa(filtro: Int, pagina: Int, cantidad: Int): [Mesa!]!
}

type Mutation {
	registrarMesa(numero: Int!): Mesa
	modificarMesa(id: ID!, numero: Int, estado: Boolean): Mesa
	eliminarMesa(id: ID!): Mesa
}
