type Pago {
	id: ID!
	serie: Int!
	numero: Int!
	fecha: DateTime!
	monto: Float!
	tipoPago: TipoPago!
	pedido: Pedido!
}

type Query {
	listarPago(pagina: Int, cantidad: Int): [Pago!]!
}

type Mutation {
	registrarPago(monto: Float!, tipoPago: ID!, pedido: ID!): Pago
	eliminarPago(id: ID!): Pago
}
