type Personal {
	id: ID!
	nombres: String!
	apellidos: String!
	sueldo: Float!
	estado: Boolean!
	cargo: Cargo!
	credencial: Credencial
	pedidosAtendidos(pagina: Int, cantidad: Int): [Pedido!]!
}

type Query {
	listarPersonal(filtro: String, pagina: Int, cantidad: Int): [Personal!]!
}

type Mutation {
	registrarPersonal(
		nombres: String!
		apellidos: String!
		sueldo: Float!
		cargo: ID!
	): Personal
	modificarPersonal(
		id: ID!
		nombres: String
		apellidos: String
		sueldo: Float
		cargo: ID
		estado: Boolean
	): Personal
	eliminarPersonal(id: ID!): Personal
}
