type Producto {
	id: ID!
	nombre: String!
	descripcion: String
	cantidad: Int!
	precio: Float!
	imagen: String!
	estado: Boolean!
	tipoProducto: TipoProducto!
	pedidosRealizados: [DetallePedido!]!
	receta(pagina: Int, cantidad: Int): [InsumoProducto!]!
}

type Query {
	listarProducto(filtro: String, pagina: Int, cantidad: Int): [Producto!]!
}

type Mutation {
	registrarProducto(
		nombre: String!
		descripcion: String
		cantidad: Int!
		precio: Float!
		imagen: String!
		tipoProducto: ID!
		receta: [InsumoProductoInput!]!
	): Producto
	modificarProducto(
		id: ID!
		nombre: String
		descripcion: String
		cantidad: Int
		precio: Float
		imagen: String
		tipoProducto: ID
		receta: [InsumoProductoInput!]
	): Producto
	eliminarProducto(id: ID!): Producto
}
