type TipoPago {
	id: ID!
	nombre: String!
	pagosPorTipo(pagina: Int, cantidad: Int): [Pago!]!
}

type Query {
	listarTipoPago: [TipoPago!]!
}

type Mutation {
	registrarTipoPago(nombre: String!): TipoPago
	modificarTipoPago(id: ID!, nombre: String, estado: Boolean): TipoPago
	eliminarTipoPago(id: ID!): TipoPago
}
